FROM arm64v8/ubuntu:22.04

RUN apt-get update && \
    apt-get install -y sudo python3 python3-pip curl net-tools openssh-client && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    apt-get clean

CMD ["sleep", "infinity"]
