---
- name: Disable swap (only if dphys-swapfile is present)
  ansible.builtin.command: dphys-swapfile swapoff
  register: swapoff_result
  changed_when: swapoff_result.rc == 0
  failed_when: swapoff_result.rc != 0
  when: ansible_facts.packages['dphys-swapfile'] is defined

- name: Remove swapfile entry from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^/var/swap'
    state: absent

- name: Remove dphys-swapfile package (if present)
  ansible.builtin.apt:
    name: dphys-swapfile
    state: absent
    purge: true
    update_cache: true

- name: Ensure cgroup flags are set in /boot/cmdline.txt
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '^(.*)$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
    insertafter: EOF
