---
- name: Disable swap
  command: dphys-swapfile swapoff
  ignore_errors: true

- name: Remove swapfile entry from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^/var/swap'
    state: absent

- name: Remove dphys-swapfile package (if present)
  apt:
    name: dphys-swapfile
    state: absent
    purge: true
    update_cache: true

- name: Ensure cgroup flags are set in /boot/cmdline.txt
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^(.*)$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
    insertafter: EOF
