---
# ========================================================================
# Playbook: Create Additional System Users
#
# This playbook allows you to define and manage additional system users
# from group_vars or host_vars. Two examples are provided:
#   - 'docker' user with passwordless sudo
#   - 'localuser' with standard access
# ========================================================================

- name: Create additional system users
  hosts: all
  become: true

  pre_tasks:
    - name: Show message if no users are defined
      ansible.builtin.debug:
        msg: "Skipping user creation play: no users were defined in 'additional_users'."
      when: additional_users is not defined or additional_users | length == 0

    - name: End play if no users are defined
      ansible.builtin.meta: end_play
      when: additional_users is not defined or additional_users | length == 0

  tasks:

    - name: Create system users
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        create_home: true
      loop: "{{ additional_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Add users to sudoers (if sudo is true)
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ item.name }}"
        content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL\n"
        mode: '0440'
      when: item.sudo | default(false)
      loop: "{{ additional_users }}"
      loop_control:
        label: "{{ item.name }}"
